name: Pull Request Checks

on:
  pull_request: ~

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v2'
      - uses: oven-sh/setup-bun@v1
      - name: 'Install Dependencies'
        run: bun install --frozen-lockfile
      - name: 'Run Linter'
        run: bun run lint
  prettier:
    name: Run Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v2'
      - uses: oven-sh/setup-bun@v1
      - name: 'Install Dependencies'
        run: bun install --frozen-lockfile
      - name: 'Run Prettier'
        run: bun run prettier:check
  jest:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v2'
      - uses: oven-sh/setup-bun@v1
      - name: 'Install Dependencies'
        run: bun install --frozen-lockfile
      - name: 'Run build'
        run: bun run build
      - name: 'Run tests'
        run: bun run test
      - name: 'Run e2e'
        run: bun run test:e2e
