name: Pull Request Checks

on:
  pull_request: ~

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Install Dependencies'
        run: npm ci
      - name: 'Run Linter'
        run: npm run lint
  prettier:
    name: Run Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Install Dependencies'
        run: npm ci
      - name: 'Run Prettier'
        run: npm run prettier:check
  jest:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Install Dependencies'
        run: npm ci
      - name: 'Run build'
        run: npm run build
      - name: 'Run tests'
        run: npm run test
      - name: 'Run e2e'
        run: npm run test:e2e
